import React from "react";
import { Link } from "react-router-dom";
import arrows from "./images/arrows.png"
import map from "./images/map.png"

const Home = () => {
  return (
    <div className="screen">

      <div className="banner">
        <div className="welcome">
          <h1 className="wel-1">Welcome to Explore</h1>
          <p className="wel-2">Something about our website and our goals,
            Information about the emissions planes create and how it affects our planet
            ...
          </p>
        </div>
      </div>

      <div className="Search">
        <div className="flight">
          <p className="text">Search by flight No.:</p>
          <input className="Search-btn" type="text" placeholder="Type here..."></input>
        </div>
        <div className="route">
          <p className="text">Search by route:</p>
          <div className="left-s">
            <input className="Search-btn" type="text" placeholder="Type here..."></input>
            <img src={arrows} className="arrows" alt="arrows" />
            <input className="Search-btn" type="text" placeholder="Type here..."></input>
            <button className="Explore-btn">Explore</button>
          </div>
        </div>
      </div>

      <div className="Map-section">
        <div className="map">
          <Link class="map-link" to="/map"><img src={map} className="map-img" alt="map" /></Link>
        </div>
        <div className="map-text-area">
          <h1 className="map-text">Follow and View information about planes on our LIVE map!</h1>
        </div>
      </div>

      <div className="info-section">
        <div className="info-box">
          <div className="circle"><h1>2,4%</h1></div>
          <a href="#" className="info-link">Of all CO2 emissions in 2018 
were generated by 
global commercial operations.</a>
        </div>
        <hr className="devider"></hr>
        <div className="info-box">
          <div className="circle"><h1>1m</h1></div>
          <a href="#" className="info-link">Flights this week</a>
        </div>
        <hr className="devider"></hr>
        <div className="info-box">
          <div className="circle"><h1>Top 10</h1></div>
          <a href="#" className="info-link">Destination this month 
based on flights. </a>
        </div>
      </div>

      <div className="Footer">
        <p className="foot">This project was created by students of Glasgow Caledonian University</p>
        <p>2023</p>
      </div>
    </div>
  )
};

export default Home;
